// This file has been automatically generated by the Unreal Header Implementation tool

#include "ExampleModModule.h"
#include "Misc/App.h"
#include "Containers/UnrealString.h"
#include <fstream>
#include <stdlib.h>
#include <string>

void FExampleModModule::StartupModule(){ }
void FExampleModModule::ShutdownModule(){ }

IMPLEMENT_GAME_MODULE(FExampleModModule, "ExampleMod");

std::string convertStr(const TCHAR* string) {
	char nameBuffer[256];
	wcstombs(nameBuffer, string, 256);
	return std::string(nameBuffer);
}

extern "C" DLLEXPORT void BootstrapModule(std::ofstream& logFile) {
	logFile << "Hello, world!" << std::endl;
	logFile << "Project Name: " << convertStr(FApp::GetProjectName()) << std::endl;
	logFile << "Branch Name: " << convertStr(GetData(FApp::GetBranchName())) << std::endl;
	logFile << "Build Version: " << convertStr(FApp::GetBuildVersion()) << std::endl;
}

